services:
  - type: web
    name: eatreal-frontend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: eatreal-backend2
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python debug.py
    startCommand: |
      python -c "import os; print('CWD:', os.getcwd()); print('Contents:', os.listdir('.'))"
      gunicorn wsgi:app --bind 0.0.0.0:10000 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    plan: free 