services:
  - type: web
    name: eatreal-backend
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && gunicorn generate_meal_plan:app --bind 0.0.0.0:10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    plan: free 