services:
  - type: web
    name: eatreal-frontend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: eatreal-backend2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.generate_meal_plan:app --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    plan: free 